server:
  port: 9090
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    url: jdbc:postgresql://localhost:5432/mtf
#    password: '12345'
#
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    database-platform: postgres
#    show-sql: 'true'
#    hibernate:
#      ddl-auto: update